name: Android CI

on:
  push:
    branches:
      - 'master'

jobs:
  apk:
    name: Generate APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build release APK
        run: bash ./gradlew assembleRelease --stacktrace
      - name: Rename release APK
        run: mv app/build/outputs/apk/release/app-release-unsigned.apk release-$(date +'%Y-%m-%d').apk
      - name: Upload release APK
        uses: actions/upload-artifact@v1
        with:
          name: app
          path: ./*.apk
