name: Create pre-release

on:
 push:
   branches:
     - 'master'

jobs:
  release:
    name: Create pre-release
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.head_commit.message, '[skip ci]')"

    steps:
      - uses: actions/checkout@v2
      
      - name: Create release name
        run: |
          export APK_NAME="release"
          echo "::set-env name=NEW_APK_NAME::$APK_NAME"
      
      - name: Rename release APK
        run: |
          ls -al
          mv "./_delete-me_.txt" "./${{ env.NEW_APK_NAME }}.txt"
          ls -al
      
      - name: Create pre-release from latest repo state
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: pre-release
          tag: pre-release
          allowUpdates: true
          prerelease: true
          artifact: "./${{ env.NEW_APK_NAME }}.txt"
