name: Android CI
env:
  NEW_APK_NAME: release $(date +'%Y-%m-%d')

on:
  push:
    branches:
      - 'master'

jobs:
  apk:
    name: Generate APK
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Create release APK name
        run: |
          export APK_NAME="release $(date +'%Y-%m-%d')"
          echo "::set-env name=NEW_APK_NAME::$APK_NAME"
    
      - uses: actions/checkout@v2
        
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      
      - name: Build release APK
        run: bash ./gradlew assembleRelease --stacktrace
      
      - name: Rename release APK
        run: |
          echo $NEW_APK_NAME
          echo ${{ env.NEW_APK_NAME }}
          mv "./app/build/outputs/apk/release/app-release-unsigned.apk" "./$NEW_APK_NAME.apk"
          ls -al
      
      - name: Persist release APK
        uses: actions/upload-artifact@v1
        with:
          name: ${{ env.NEW_APK_NAME }}
          path: "./${{ env.NEW_APK_NAME }}.apk"
