name: Android CI

on:
  push:
    branches:
      - 'master'

jobs:
  apk:
    name: Generate APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build release APK
        run: bash ./gradlew assembleRelease --stacktrace
      - name: Rename release APK
        run: |
          set -x
          NEW_APK_NAME="release-$(date +'%Y-%m-%d')"
          echo $NEW_APK_NAME
          echo `::set-env name=NEW_APK_NAME::$NEW_APK_NAME`
          mv "./app/build/outputs/apk/release/app-release-unsigned.apk" "./release.apk"
          ls -al
      - name: Upload release APK
        uses: actions/upload-artifact@v1
        with:
          name: release
          path: "./release.apk"
